version: '3'

services:
    app:
        image: project/${PROJECT_NAME}:${PROJECT_VERSION}
        build: ./etc/docker
        hostname: ${VIRTUAL_HOST}
        container_name: app_${PROJECT_NAME}
        working_dir: /src
        volumes:
            - ${PWD}:/src
        environment:
            - USER_ID=${UID}
            - USER_NAME=${USER_NAME}
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=80
        dns:
            - 172.16.0.53
        depends_on:
            - mysql
        networks:
            - nginx-proxy # Link to nginx-proxy network, handled by `docker/docker-compose.nginx-proxy.yml` and run by `make` at `start`, see the `networks` section below.
            - default

    hosts:
        image: ubuntu:16.04
        environment:
            - USER_ID=0
        volumes:
            - ${ETC}:${HOSTS_ETC}
            - ${PWD}:/src
        command: "/bin/true"

    php-cli:
        image: php-cli:custom
        build: ./etc/docker/php
        working_dir: /src
        user: ${UID}
        environment:
            - ENV=${ENV}
            - USER_ID=${UID}
            - USER_NAME=${USER_NAME}
        volumes:
            - ${PWD}:/src

    mysql:
        image: mysql:8.0
        container_name: sql_${PROJECT_NAME}
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        user: ${UID}
        volumes:
            - ${PWD}/var/data/mysql:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=${DATABASE_NAME}
            - USER_ID=${UID}
            - USER_NAME=${USER_NAME}

    node:
        image: node:10.15.3
        working_dir: /src
        volumes:
            - ${NPM_CACHE}:/.npm
            - ${PWD}:/src
        environment:
            - USER_ID=${UID}
            - USER_NAME=${USER_NAME}

    composer:
        image: composer:1.10.17
        working_dir: /src
        user: ${UID}
        volumes:
            #- ./composer.passwd:/etc/passwd
            - ${PWD}:/src:rw
            - ${COMPOSER_CACHE}:/.composer
        environment:
            - PATH=/composer/bin:${PATH}
            - COMPOSER_HOME=/composer/.composer
            - COMPOSER_CACHE_DIR=/.composer
            - COMPOSER_ALLOW_SUPERUSER=1
            - USER_ID=${UID}
            - USER_NAME=${USER_NAME}
            - GROUP_ID=${GID}
networks:
    nginx-proxy:
        external:
            name: ${DOCKER_NETWORK}_default
